### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by lauw0129** [marvinvr/ombi-mobile#110]
![IMG_20210523_002142](https://user-images.githubusercontent.com/62137079/119233779-201c2480-bb5d-11eb-8742-fda7fbafce0b.jpg)
When I add to the home screen and try to run, this appeared. But It is working for just using chrome. I hope you will update for it. Thank you

**Comment by marvinvr** [comment]
This shouldn't be occurring anymore. Make sure you use the correct url: https://ombi-mobile.marvinvr.dev
