### ISSUE TITLE
Pre-configured Ombi Server URL

### ISSUE THREAD

**Issue by jflix89** [marvinvr/ombi-mobile#119]
The most complicated part of getting friends/family to use this is having them manually input the URL for my Ombi server, if I could have that pre-configured on my self-hosted container that would be great.

Even if I just need to manually edit the image myself, I just don't know how to do that.

**Comment by marvinvr** [comment]
Good Idea! Thanks for the input! Was also thinking about adding a URL Parameter to pre-fill the URL to the Ombi Instance, which you can then share.

**Comment by marvinvr** [comment]
@jflix89 This is now possible as of the latest release. More details can be found in the [Release Notes].(https://github.com/marvinvr/ombi-mobile/releases/tag/2.2.0)
